const WORD_LIST = [
    // --- Lugares Comunes ---
    { word: "Cine", clue: "Pareja" },
    { word: "Playa", clue: "Horizonte" },
    { word: "Restaurante", clue: "Mesa" },
    { word: "Biblioteca", clue: "Ficha" },
    { word: "Aeropuerto", clue: "Espera" },
    { word: "Supermercado", clue: "Pasillo" },
    { word: "Gimnasio", clue: "Energía" },
    { word: "Hospital", clue: "Pijama" },
    { word: "Museo", clue: "Silencio" },
    { word: "Parque", clue: "Banqueta" },
    
    // --- La mejor parte ---
    { word: "Calva de Jesús", clue: "Brillante" },
    { word: "As amigas de Marcos", clue: "Sexy" },
    { word: "Gemini", clue: "Parte" },
    { word: "Parte", clue: "Clase" },
    { word: "Amperios", clue: "Circuito" },
    { word: "Eloy o bolas", clue: "Lesbiana" }, 
    { word: "Marcos gay", clue: "Orgullo" },
    { word: "Perilla de Iker", clue: "Pelo" },
    { word: "Antonio", clue: "Desgracia" },
    { word: "Porno", clue: "Privado" },
    { word: "Osciloscopio", clue: "Medir" },
    { word: "Firulais", clue: "Vicio" },
    { word: "Andrés", clue: "Gato" },
    { word: "Torres gemelas", clue: "Miedo" },
    { word: "Chouza", clue: "Papeles" },
    { word: "Rachel", clue: "Te jodes, no hay pista en esta" },
    { word: "Monjas", clue: "Exilio" },
    { word: "Cortocircuito", clue: "Fallo" },
    { word: "Conmutador", clue: "Puente" },
    { word: "Coño", clue: "Deseo" },
    { word: "Polla", clue: "Comida" }, // para joder al impostor
    { word: "Prácticas", clue: "Montaje" },
    { word: "Telecomunicaciones", clue: "Infernal" },
    { word: "Nintendo Switch", clue: "Entretenimiento" },
    { word: "Amperios", clue: "Circuito" },
    { word: "Lesbiana", clue: "Bollo" },
    { word: "Tetas", clue: "Esfera" },
    { word: "Pedofilia", clue: "Niño" },
    { word: "Amperios", clue: "Circuito" },
    { word: "Feto", clue: "Nombra a alguien de la clase" },
    { word: "Mexicano", clue: "Mono" },
    { word: "Gafas de Marcos", clue: "Nerd" },
    { word: "Pou", clue: "Nostalgia" },
    { word: "PSVITA", clue: "Viejo" },
    { word: "Teclado", clue: "Roto" },
    { word: "Impostor", clue: "Soy yo" }, // Muejejeje
    { word: "Abuela", clue: "Cachonda" },
    { word: "Masturbación", clue: "Guarrada" },
    { word: "Puticlub", clue: "Luces" },
    { word: "Culazo / Culo", clue: "Deseable" },
    { word: "Negativo", clue: "Inglés" },
    { word: "Cobre", clue: "Robar" },
    { word: "Cojones", clue: "Doloroso" },
    { word: "Orgasmo", clue: "Intentar hacerlo" },
    { word: "Vaper", clue: "Frutas" },
    { word: "David", clue: "Excusa de Rivas" },
];
